### ISSUE TITLE
Feature request: Add Date attribute

### ISSUE THREAD

**Issue by cmcinroy** [SaraVieira/awesome-talks#102] opened 2018-06-20 11:06 UTC
Would be great to be able to filter/sort by date of the talk.

Perhaps default to the date posted?... could be overridden if for some reason the actual date of the talk is known and is more accurate.

Love the site/concept.

**Comment by pksjce** [comment] 2018-06-25 02:34
Would be great to have this. At some point, we plan to have a filter feature. Would be useful for that. https://github.com/SaraVieira/awesome-talks/issues/101

**Comment by sahitpj** [comment] 2018-07-05 12:58
I would like to work on this, if the issue is still active !

**Comment by SaraVieira** [comment] 2018-07-05 15:02
I just merged it sorry :(

closed by https://github.com/SaraVieira/awesome-talks/pull/105

**Closed by SaraVieira** 2018-07-05 15:02 UTC
Labels: enhancement, good first issue
